import { EngineConfigurationOption, Text } from '@sonolus/core'

export const optionsDefinition = {
    speed: {
        name: Text.Speed,
        standard: true,
        advanced: true,
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    hidden: {
        name: Text.Hidden,
        standard: true,
        advanced: true,
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    noteSpeed: {
        name: Text.NoteSpeed,
        scope: 'cgss',
        type: 'slider',
        def: 6,
        min: 1,
        max: 10,
        step: 0.1,
    },
    attribute: {
        name: 'Attribute',
        description: "Currently not implemented",
        scope: 'cgss',
        type: 'select',
        def: 0,
        values: ['Original', 'Cute', 'Cool', 'Passion'] as string[],
    },
    mirror: {
        name: Text.Mirror,
        type: 'toggle',
        def: 0,
    },
    sfxEnabled: {
        name: Text.Effect,
        scope: 'cgss',
        type: 'toggle',
        def: 1,
    },
    autoSFX: {
        name: Text.EffectAuto,
        scope: 'cgss',
        type: 'toggle',
        def: 0,
    },
    // noteSize: {
    //     name: Text.NoteSize,
    //     scope: 'cgss',
    //     type: 'slider',
    //     def: 1,
    //     min: 0.1,
    //     max: 2,
    //     step: 0.05,
    //     unit: Text.PercentageUnit,
    // },
    noteEffectEnabled: {
        name: Text.NoteEffect,
        scope: 'cgss',
        type: 'toggle',
        def: 1,
    },
    connectorAlpha: {
        name: Text.ConnectorAlpha,
        scope: 'cgss',
        type: 'slider',
        def: 0.5,
        min: 0.1,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    connectorQuality: {
        name: "Connector Quality",
        scope: 'cgss',
        type: 'slider',
        def: 20,
        min: 10,
        max: 50,
        step: 1
    },
} satisfies Record<string, EngineConfigurationOption>
