name: Sync Engine Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  master:
    name: Update Build

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Clone CGSS Sonolus Data
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: git clone "https://gorenganhunter:$TOKEN@github.com/gorenganhunter/cgss-sonolus-data.git"
       
      - name: Clone CGSS Server
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: git clone "https://gorenganhunter:$TOKEN@github.com/gorenganhunter/cgss-server.git"
      #
      # - name: Clone D4C
      #   env:
      #     TOKEN: ${{ secrets.GH_TOKEN }}
      #   run: git clone "https://gorenganhunter:$TOKEN@github.com/gorenganhunter/d4c.git"
      
      # - name: Clone Level Packer
      #   env:
      #     TOKEN: ${{ secrets.GH_TOKEN }}
      #   run: git clone "https://gorenganhunter:$TOKEN@github.com/gorenganhunter/sonolus-cgss-level-packer.git"
          
      - name: Use Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build engine
        run: npm run build

      - name: Publish NPM
        run: npm publish
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Update Dependencies
      #   run: |
      #     cd sonolus-cgss-level-packer
      #     npm install sonolus-cgss-engine@latest

      - name: Update build
        run: node update.cjs

      - name: Preparing Git
        run: |
          git config --global user.name "gorenganhunter"
          git config --global user.email "gorengandev@gmail.com"

      - name: Push Data
        run: |
          cd cgss-sonolus-data
          git add .
          git commit -m "Auto Update"
          git push
      
      # - name: Push Packer
      #   run: |
      #     cd sonolus-cgss-level-packer
      #     git add .
      #     git commit -m "Auto Update"
      #     git push
      
      - name: Push Server
        run: |
          cd cgss-server
          git add .
          git commit -m "Auto Update"
          git push

      # - name: Push Custom Server
      #   run: |
      #     cd d4c
      #     git add .
      #     git commit -m "Auto Update"
      #     git push
